apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-rs
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: sample-rs-app
  template:
    metadata:
      labels:
        app: sample-rs-app
    spec: 
      containers:
        - name: nginx-container
          image: nginx:1.12
          ports:
            - containerPort: 80